version: '3.8'

services:

  keep-rocking:
    restart: unless-stopped
    # depends_on:
    #     - backend
    # links:
    #     - "nginx-dev:api.${DOMAIN}"
    build:
        context: .
        dockerfile: dev.Dockerfile
    env_file:
      - ./.envs/.local/.env
    environment:
        BASE_API_URL: http://api.dev.${DOMAIN}
    volumes:
        - node_modules:/app/node_modules
        - .:/app
    ports:
        - 8080:3000
volumes:
    node_modules: