version: '3.8'

services:

  keep-rocking:
    restart: unless-stopped
    # depends_on:
    #     - backend
    # links:
    #     - "nginx-dev:api.${DOMAIN}"
    build:
        context: .
        dockerfile: dev.Dockerfile
    env_file:
      - .envs/.local/.env
      - .envs/.prod/.env
    stdin_open: true
    volumes:
        - .:/app
    ports:
        - 8080:3000
